services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env                 # load environment variables from .env file
    networks:
      - chatnet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge